### ISSUE TITLE
Multiple memory leaks as reported by clang's LeakSanitizer

### ISSUE THREAD

**Issue by opennota** [graphql/libgraphqlparser#19]
Build `dump_json_ast` with `-fsanitize=address` on Linux x86_64:

```
$ clang --version
clang version 3.7.0 (https://github.com/llvm-mirror/clang.git 40b68b4c02b9d9e1e4138815747adf5589496240) (https://github.com/llvm-mirror/llvm.git dccade93466c50834dbaa5f4dabb81e90d768c40)
Target: x86_64-unknown-linux-gnu
Thread model: posix

$ mkdir build && cd build

$ env CXX=clang++ CXXFLAGS='-fsanitize=address -ggdb' cmake ..

$ make
```

and execute the following command:

```
$ echo -ne '\x7b\x0a\x20\x75\x30\x30\x30\x28\x69\x30\x3a\x20\x39\x30\x45' | ./dump_json_ast
```

Output:

```
Parser failed with error: 2.14: syntax error, unexpected EOF, expecting :

=================================================================
==5216==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x4df280 in operator new(unsigned long) llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:62
    #1 0x7f5672faabc6 in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:232:28
    #2 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #3 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #4 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #5 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4df280 in operator new(unsigned long) llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:62
    #1 0x7f5672fadc7f in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:329:36
    #2 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #3 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #4 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #5 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4df280 in operator new(unsigned long) llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:62
    #1 0x7f5672fadefd in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:333:32
    #2 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #3 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #4 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #5 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x4df280 in operator new(unsigned long) llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:62
    #1 0x7f5672faebcb in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:363:32
    #2 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #3 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #4 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #5 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x4df280 in operator new(unsigned long) llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:62
    #1 0x7f5672faabc6 in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:232:28
    #2 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #3 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #4 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #5 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

Indirect leak of 10 byte(s) in 3 object(s) allocated from:
    #0 0x477266 in __interceptor_strdup llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:590
    #1 0x7f5672faac75 in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:232:59
    #2 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #3 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #4 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #5 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x4df280 in operator new(unsigned long) llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:62
    #1 0x7f5672fc307b in __gnu_cxx::new_allocator<std::unique_ptr<facebook::graphql::ast::Argument, std::default_delete<facebook::graphql::ast::Argument> > >::allocate(unsigned long, void const*) /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/ext/new_allocator.h:104:27
    #2 0x7f5672fc2c96 in std::_Vector_base<std::unique_ptr<facebook::graphql::ast::Argument, std::default_delete<facebook::graphql::ast::Argument> >, std::allocator<std::unique_ptr<facebook::graphql::ast::Argument, std::default_delete<facebook::graphql::ast::Argument> > > >::_M_allocate(unsigned long) /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/bits/stl_vector.h:168:27
    #3 0x7f5672fc20bb in void std::vector<std::unique_ptr<facebook::graphql::ast::Argument, std::default_delete<facebook::graphql::ast::Argument> >, std::allocator<std::unique_ptr<facebook::graphql::ast::Argument, std::default_delete<facebook::graphql::ast::Argument> > > >::_M_emplace_back_aux<facebook::graphql::ast::Argument*&>(facebook::graphql::ast::Argument*&) /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/bits/vector.tcc:404:22
    #4 0x7f5672fb4d6a in void std::vector<std::unique_ptr<facebook::graphql::ast::Argument, std::default_delete<facebook::graphql::ast::Argument> >, std::allocator<std::unique_ptr<facebook::graphql::ast::Argument, std::default_delete<facebook::graphql::ast::Argument> > > >::emplace_back<facebook::graphql::ast::Argument*&>(facebook::graphql::ast::Argument*&) /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/bits/vector.tcc:101:4
    #5 0x7f5672fadd6b in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:329:82
    #6 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #7 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #8 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #9 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

Indirect leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x477266 in __interceptor_strdup llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:590
    #1 0x7f5672faec59 in yy::GraphQLParserImpl::parse() libgraphqlparser/build/parser.ypp:363:61
    #2 0x7f5672fd991b in facebook::graphql::doParse(char const**, void*) libgraphqlparser/GraphQLParser.cpp:26:17
    #3 0x7f5672fd9c0c in facebook::graphql::parseFile(_IO_FILE*, char const**) libgraphqlparser/GraphQLParser.cpp:48:17
    #4 0x4e222f in main libgraphqlparser/dump_json_ast.cpp:35:14
    #5 0x7f5671d89aa4 in __libc_start_main (/lib64/libc.so.6+0x21aa4)

SUMMARY: AddressSanitizer: 293 byte(s) leaked in 11 allocation(s).
```

#afl

**Comment by swolchok** [comment]
I used valgrind, but reproed similar issues. Thanks for pointing this out!
